### ISSUE TITLE
Crash @ end of Trade

### ISSUE THREAD

**Issue by Haasetyle** [AlphaConsole/AlphaConsoleElectron#32]
Game force closes after completing a trade. 
I believe it happens when writing to txt file to keep track of trades. 
I have Laptop and desktop with completely different specs and this happens on both. 
It only happens once both parties have accepted the trade. It does complete the trade however it takes you to desktop and force closes the game.

**Comment by Kermalis** [comment]
This issue has nothing to do with the UI; it is a bug between Psyonix's dumb code and the mod. None of the devs can even reproduce it for the past two updates, and crash reports are not helping. Either way, this issue does not belong here.
