### ISSUE TITLE
Alpha consles version isnt compatable with new season rocket league

### ISSUE THREAD

**Issue by Adeoye2417** [AlphaConsole/AlphaConsoleElectron#38]
Hi im new to pc just my point is that ive updated rocket league but the recent alpha consle doesn't appear to work and gives a risk of crashes have accepted but the game still dosent work is there a new version coming

**Comment by DOUNDEA** [comment]
its happening the same for me. pls help

**Comment by Adeoye2417** [comment]
> its happening the same for me. pls help

We should try contact them via discord

**Comment by nitrog0d** [comment]
or you guys should just wait for an update...

**Comment by KurojakiKaoru** [comment]
Alpha Console is Updated.

**Comment by HaydenMeloche** [comment]
fixed https://github.com/AlphaConsole/AlphaConsoleElectron/releases/tag/v9.9.15
