### ISSUE TITLE
Corrupted Downloads

### ISSUE THREAD

**Issue by Barbosicks** [AlphaConsole/AlphaConsoleElectron#4]
If people close the Texture window before finishing a texture package download it will crash their game.

Possible solution: downloading as temp and only copying to textures AFTER download complete.

**Comment by jd0920** [comment]
@Barbosicks Are you saying downloading the required files to a `tmp/` folder? Sorry for my confusion :stuck_out_tongue:

**Comment by Barbosicks** [comment]
Ye something like that.

**Comment by Barbosicks** [comment]
Solved in fdccc8652cba49ea0b2f593a7a1c6cb3f45d4199
