### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by czifro** [AlphaConsole/AlphaConsoleElectron#47]
Hi,

Is there any plan to make this cross-platform to support Linux/MacOS? Personally, I'm on MacOS and I would like to try out alpha console on rocket league.

Thanks!

**Comment by test137E29B** [comment]
Hi,

Currently there are no plans to make a Port of AlphaConsole for Mac or Linux Operating systems. Mac and Linux use a different type of Library linking to Windows and thus would require to keep two versions of AlphaConsole in sync with each other.

You can however use Bootcamp on a Mac to install Steam and Rocket League on a Windows install alongside MacOS. You can use AlphaConsole on this.

For more information on how to do that stuff, visit the Discord server.

\- Nameless

**Comment by czifro** [comment]
I understand. Thank you for the quick reply. I'll close the issue.
