### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JerkStoleMyName** [AlphaConsole/AlphaConsoleElectron#56]
I know this isn't an issue, and I apologize, but this is my first time using Alpha Console and I see that Car Body displays as an option, but only allows you (or perhaps just me) to choose Unchanged.  Is there a specific way to use this feature, or will this be added at some point in the future?  If not, is there a particular reason why it isn't available?  I would personally love the feature, even taking into consideration the difference in hitbox.

**Comment by nitrog0d** [comment]
That's for custom textures, click the big button called "GET TEXTURES" and download some body skins, they'll appear there.
We don't have plans for adding body changing feature.

**Comment by JerkStoleMyName** [comment]
Okay, thanks for letting me know!
