### ISSUE TITLE
RL crashes when AC is Enabled

### ISSUE THREAD

**Issue by MAVRIKO** [AlphaConsole/AlphaConsoleElectron#6]
When alpha console is enabled RL crashes after "Press any button" screen. I have tried this on 2 devices with current configs:

i5-6200u
8GB DDR3
intel hd 520

FX-6300
16GB DDR3
R9-270

As crash happens AC items are applied. no errors are reported. crashes whether AC is open or closed.
I have tried having AC disabled and enabling it after seeing main menu and it still forces a crash.

**Comment by coledeb** [comment]
Please don't use this for bug reports, rather use #beta-help channel in our discord.  If you aren't using the beta, this is not a relevant project either way at the moment for your issues.
