### ISSUE TITLE
Can't rotate car in garage when using controller

### ISSUE THREAD

**Issue by BabbelGaming** [AlphaConsole/AlphaConsoleElectron#70]
I can't rotate my car in garage when using Xbox controller. With AlphaConsole disabled it works.

**Comment by C-Lodder** [comment]
This was fixed in v9.15.5: https://github.com/AlphaConsole/AlphaConsoleElectron/releases/tag/v9.15.5

**Comment by HaydenMeloche** [comment]
yes thanks @C-Lodder
